module Bpod
  # Bing markets (i.e. regions)
  REGIONS = {
    'es-AR' => 'Argentina',
    'en-AU' => 'Australia',
    'de-AT' => 'Austria',
    'nl-BE' => 'Belgium - Dutch',
    'fr-BE' => 'Belgium - French',
    'pt-BR' => 'Brazil',
    'en-CA' => 'Canada - English',
    'fr-CA' => 'Canada - French',
    'fr-FR' => 'France',
    'de-DE' => 'Germany',
    'zh-HK' => 'Hong Kong S.A.R',
    'en-IN' => 'India',
    'en-ID' => 'Indonesia',
    'it-IT' => 'Italy',
    'ja-JP' => 'Japan',
    'ko-KR' => 'Korea',
    'en-My' => 'Malaysia',
    'es-MX' => 'Mexico',
    'nl-NL' => 'Netherlands',
    'nb-NO' => 'Norway',
    'zh-CN' => 'People\'s Republic of China',
    'pl-PL' => 'Poland',
    'ru-RU' => 'Russia',
    'ar-SA' => 'Saudi Arabia',
    'en-ZA' => 'South Africa',
    'es-ES' => 'Spain',
    'sv-SE' => 'Sweden',
    'fr-CH' => 'Switzerland - French',
    'de-CH' => 'Switzerland - German',
    'zh-TW' => 'Taiwan',
    'tr-TR' => 'Turkey',
    'en-GB' => 'United Kingdom',
    'en-US' => 'United States - English',
    'es-US' => 'United States - Spanish'
  }
end